### ISSUE TITLE
Add BaseConnector to existing connectors 

### ISSUE THREAD

**Issue by mingazhev** [happy-travel/agent-app-project#1157]
Manual:
https://github.com/happy-travel/base-connector/

Example:
https://github.com/happy-travel/travelgatex-connector/pull/177/files

Connectors (some may have added base connector already)
- [x] happy-travel/agent-app-project#1185
- [x] #1202
- [x] #1213
- [x] #1229
- [x] happy-travel/agent-app-project#1178
- [x] happy-travel/agent-app-project#1179
- [x] happy-travel/bronevik-connector#175
